name: TIS - Pipeline

on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Install dependencies
      #   run: npm install --no-audit --no-fund --no-optional

      # - name: Test unit
      #   run: npm test
      - name: Build
        env:
          NETLIFY_SITE_ID : ${{ secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN : ${{ secrets.NETLIFY_AUTH_TOKEN}}
        run : |
          npm run build
          npx netlify-cli deploy --dir=build --prod